apiVersion: v1
kind: Service
metadata:
  name: notice-api-svc
  namespace: notice
spec:
  selector:
    app: notice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort